version: "3.9"

services:
  api:
    build:
      context: ./express-api
    ports:
      - "3000:3000"
    env_file:
      - ./express-api/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
